### ISSUE TITLE
Bug when deserializing

### ISSUE THREAD

**Issue by alexalok** [alexalok/AppleReceiptVerifier.NET#4]
```
System.Text.Json.JsonException: The JSON value could not be converted to AppleReceiptVerifierNET.Models.ReceiptInfo. Path: $.latest_receipt_info[0].in_app_ownership_type | LineNumber: 6 | BytePositionInLine: 760.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.ReadAsPropertyNameCore(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.NullableConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryReadAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state, Object& value)
   at System.Text.Json.Serialization.Converters.LargeObjectWithParameterizedConstructorConverter`1.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryReadAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state, Object& value)
   at System.Text.Json.Serialization.Converters.LargeObjectWithParameterizedConstructorConverter`1.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at AppleReceiptVerifierNET.AppleReceiptVerifier.VerifyReceiptInternalAsync(String environmentUrl, String requestBodyJson)
   at AppleReceiptVerifierNET.AppleReceiptVerifier.VerifyReceiptAsync(String receiptData, Boolean excludeOldTransactions)
   at PurchaseStatsUploader.Works.SubscriptionsChecker.ProcessSubscription(SubscriptionWithMetadata sub) in /src/PurchaseStatsUploader/Works/SubscriptionsChecker.cs:line 116
   at PurchaseStatsUploader.Works.SubscriptionsChecker.ExecuteIterationAsync(CancellationToken ct, IAppleReceiptVerifier verifier, IDbConnection db, IAppMetricaUploader appMetrica) in /src/PurchaseStatsUploader/Works/SubscriptionsChecker.cs:line 43
   at dotWork.WorkHost`2.ExecuteAsynchronousIteration(Object[] arguments)
   at dotWork.WorkHost`2.ExecuteIterationInternal(Object[] arguments)
   at dotWork.WorkHost`2.ExecuteIterationSafe(CancellationToken stoppingToken)
```

**Comment by alexalok** [comment]
Seems that snake_case enum values are not natively supported by .NET Oo
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-6-0#support-enum-string-value-deserialization
